# Generated by Django 4.1 on 2022-11-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='findermodel',
            name='latitude',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='findermodel',
            name='longitude',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
