# Generated by Django 4.1 on 2022-11-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_findermodel_latitude_findermodel_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findermodel',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='findermodel',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
